/* Local UI verification. Use an installed Playwright package via NODE_PATH. All external requests are fixtures. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs/promises');
const path = require('node:path');

async function main() {
  const root = path.resolve(__dirname, '..');
  const output = path.join(root, 'test-results');
  await fs.mkdir(output, { recursive: true });
  const assets = new Set(['index.html', 'styles.css', 'app.js', 'record-client.js', 'session.js']);
  const server = http.createServer(async (request, response) => {
    const filename = new URL(request.url, 'http://localhost').pathname.replace(/^\/troll-builde\//, '') || 'index.html';
    if (!assets.has(filename)) { response.writeHead(404); response.end(); return; }
    response.setHeader('Content-Type', filename.endsWith('.html') ? 'text/html; charset=utf-8' : filename.endsWith('.css') ? 'text/css' : 'application/javascript');
    response.end(await fs.readFile(path.join(root, filename)));
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  let browser;
  try {
    browser = await chromium.launch({ channel: 'msedge', headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [], requests = [];
    let failMatches = false, activeProfiles = 0, maxProfiles = 0;
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => requests.push(request.url()));
    await page.route('**/*', async route => {
      const url = new URL(route.request().url());
      if (url.hostname === '127.0.0.1') return route.continue();
      if (url.pathname.includes('lucide')) return route.fulfill({ contentType: 'application/javascript', body: 'window.lucide={createIcons(){}}' });
      if (url.pathname.includes('chart.js')) return route.fulfill({ contentType: 'application/javascript', body: 'window.Chart=class{destroy(){}}' });
      let data;
      if (url.pathname === '/api/versions.json') data = ['16.20.1'];
      else if (url.pathname === '/common/season-list') data = { season_list: [27] };
      else if (url.pathname === '/common/champion-info') data = { champions: [{ champion_id: '86', champion_name_en: 'Garen', champion_name_kr: '가렌' }] };
      else if (url.pathname === '/summoner/summoner') {
        const name = decodeURIComponent(url.searchParams.get('riot_id_name'));
        if (name === 'Broken') return route.fulfill({ status: 404, contentType: 'application/json', body: '{}' });
        activeProfiles++; maxProfiles = Math.max(maxProfiles, activeProfiles);
        await new Promise(resolve => setTimeout(resolve, 50));
        activeProfiles--;
        data = { summoner_basic_info_dict: { puu_id: `provider-${name}`, profile_id: 29, level: 123, previous_season_tier_list: [{ season: 25, tier: 'GOLD', division: 2, lp: 40 }] } };
      } else if (url.pathname === '/summoner/summoner-realtime') data = { season_tier_info_dict: { ranked_solo_5x5: { tier: 'DIAMOND', division: 3, league_points: 55, wins: 20, losses: 10 } } };
      else if (url.pathname === '/summoner/champion-stat') data = { counter_champion_stats: { total: { enemy_champion_stats: { All: [{ champion_id: '86', games: 10, win_rate: 60, kda: 3.5 }] } } } };
      else if (url.pathname === '/match/matches') {
        if (failMatches) return route.fulfill({ status: 503, contentType: 'application/json', body: '{}' });
        data = { match_json_list: [{ match_basic_dict: { queue_id: 420, game_duration: 1800, creation_timestamp: 1790000000 }, participants_list: [{ puu_id: url.searchParams.get('puu_id'), champion_id: 86, is_win: true, final_stat_dict: { kills: 8, deaths: 3, assists: 7 } }] }] };
      }
      if (data) return route.fulfill({ contentType: 'application/json', body: JSON.stringify(data) });
      return route.fulfill({ status: 204, body: '' });
    });
    const base = `http://127.0.0.1:${server.address().port}/troll-builde/`;
    await page.goto(base);
    assert.equal(await page.locator('#setup-page').isVisible(), true);
    assert.equal(await page.locator('#auction-page').isVisible(), false);
    await page.screenshot({ path: path.join(output, 'landing-desktop.png'), fullPage: true, animations: 'disabled' });
    await page.getByRole('button', { name: '경매 준비하기' }).click();
    assert.match(await page.locator('#setup-error').innerText(), /각각 한 명 이상/);
    await page.getByRole('textbox', { name: '팀장 1 Riot ID', exact: true }).fill('Captain One#KR1');
    await page.getByRole('textbox', { name: '팀장 2 Riot ID', exact: true }).fill('Captain Two#KR1');
    await page.getByRole('spinbutton', { name: '팀장 1 예산', exact: true }).fill('900');
    await page.getByRole('spinbutton', { name: '팀장 2 예산', exact: true }).fill('0');
    await page.getByRole('textbox', { name: '참가자 1 Riot ID', exact: true }).fill('captain one#kr1');
    await page.getByRole('button', { name: '경매 준비하기' }).click();
    assert.match(await page.locator('#setup-error').innerText(), /중복 등록/);
    const unsafeName = '<img src=x onerror="window.inputExecuted=true">';
    await page.getByRole('textbox', { name: '참가자 1 Riot ID', exact: true }).fill(`${unsafeName}#KR1`);
    await page.getByRole('textbox', { name: '참가자 2 Riot ID', exact: true }).fill('Player Two#KR1');
    await page.getByRole('textbox', { name: '참가자 3 Riot ID', exact: true }).fill('Broken#KR1');
    await page.getByRole('button', { name: '경매 준비하기' }).click();
    assert.equal(await page.locator('.player-card').count(), 3);
    assert.equal(await page.locator('.team-auction-card').count(), 2);
    assert.equal(await page.evaluate(() => window.inputExecuted), undefined);
    const before = await page.evaluate(() => ({ ids: state.allPlayers.map(p => p.client_id), providerIds: state.allPlayers.map(p => p.puu_id) }));
    assert.equal(new Set(before.ids).size, 3);
    assert.ok(before.providerIds.every(id => id === null));
    await page.locator('.player-card').filter({ hasText: 'Player Two' }).getByRole('button', { name: '경매 올리기' }).click();
    assert.equal(await page.locator('.player-card').count(), 2);
    await page.locator('#bid-amount').fill('50');
    await page.locator('#btn-bid-confirm').click();
    assert.equal(await page.locator('.roster-slot.filled').count(), 1);
    const drafted = await page.evaluate(() => ({ id: state.teams[0].roster[0].client_id, budget: state.teams[0].budget }));
    assert.equal(drafted.budget, 850);
    await page.locator('.player-card').filter({ hasText: unsafeName }).getByRole('button', { name: '경매 올리기' }).click();
    await page.locator('#bid-team-select').selectOption('1');
    await page.locator('#bid-amount').fill('0');
    await page.locator('#bid-amount').dispatchEvent('input');
    await page.locator('#btn-update-all').click();
    await page.waitForFunction(() => !updatingAll && !activeUpdates);
    assert.match(await page.locator('#update-progress').innerText(), /성공 4명 · 실패 1명/);
    assert.equal(maxProfiles, 2);
    assert.equal(await page.locator('#bid-team-select').inputValue(), '1');
    assert.equal(await page.locator('#bid-amount').inputValue(), '0');
    assert.deepEqual(await page.evaluate(() => ({ id: state.teams[0].roster[0].client_id, budget: state.teams[0].budget })), drafted);
    assert.equal(await page.evaluate(() => state.teams[0].roster[0] === state.allPlayers.find(p => p.client_id === state.teams[0].roster[0].client_id)), true);
    assert.equal(await page.evaluate(() => window.inputExecuted), undefined);
    assert.ok(!requests.some(address => /players_(?:input|data)\.json/.test(address)));
    const playerTwo = page.locator('.participant-record').filter({ hasText: 'Player Two#KR1' });
    await playerTwo.locator('.participant-name').click();
    assert.equal(await page.locator('#player-modal').isVisible(), true);
    await page.locator('#tab-season-history').click();
    const successfulAt = await page.evaluate(() => currentModalPlayer.updated_at);
    failMatches = true;
    await page.locator('#btn-modal-refresh').click();
    await page.waitForFunction(() => !activeUpdates);
    assert.equal(await page.evaluate(() => currentModalTab), 'season');
    assert.equal(await page.evaluate(() => currentModalPlayer.updated_at), successfulAt);
    assert.match(await page.locator('#modal-record-status').innerText(), /기존 .* 조회 결과 유지/);
    failMatches = false;
    await page.locator('#btn-modal-refresh').click();
    await page.waitForFunction(() => !activeUpdates);
    assert.equal(await page.evaluate(() => currentModalPlayer.record_status), 'ready');
    assert.equal(await page.evaluate(() => currentModalPlayer.solo_lp_graph.data.length), 2);
    await page.locator('#btn-close-modal').click();
    await page.locator('#btn-bid-confirm').click();
    assert.equal(await page.locator('.roster-slot.filled').count(), 2);
    await page.locator('.roster-release-btn').first().click();
    await page.locator('#btn-confirm-ok').click();
    assert.equal(await page.evaluate(() => state.teams[0].budget), 900);
    await page.locator('#btn-random-pick').click();
    await page.locator('#btn-bid-pass').click();
    await page.locator('#btn-confirm-ok').click();
    assert.equal(await page.evaluate(() => state.nominatedPlayer), null);
    await page.screenshot({ path: path.join(output, 'auction-desktop.png'), fullPage: true, animations: 'disabled' });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: path.join(output, 'auction-mobile.png'), fullPage: true, animations: 'disabled' });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    await page.locator('#btn-edit-participants').click();
    await page.screenshot({ path: path.join(output, 'landing-mobile.png'), fullPage: true, animations: 'disabled' });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    await page.locator('#btn-cancel-setup').click();
    assert.equal(await page.locator('.roster-slot.filled').count(), 1);
    await page.locator('#btn-edit-participants').click();
    await page.getByRole('button', { name: '경매 준비하기' }).click();
    assert.equal(await page.locator('.roster-slot.filled').count(), 0);
    assert.equal(await page.evaluate(() => state.allPlayers.find(p => p.riot_id_name === 'Player Two').record_status), 'ready');
    assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length), 0);
    await page.reload();
    assert.equal(await page.locator('#setup-page').isVisible(), true);
    assert.equal(await page.getByRole('textbox', { name: '팀장 1 Riot ID', exact: true }).inputValue(), '');
    assert.deepEqual(errors, []);
    console.log('Browser smoke passed: subpath assets, setup validation, unqueried auction, batch/individual refresh, retries, preserved assignments, edit, reset-on-reload, desktop/mobile layout.');
  } finally {
    if (browser) await browser.close();
    await new Promise(resolve => server.close(resolve));
  }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
